// <auto-generated />
using System;
using BankSimulator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankSimulator.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190216182952_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankSimulator.API.Models.Account", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthdate");

                    b.Property<decimal>("Cash");

                    b.Property<int?>("CreditHistoriesIDCredit");

                    b.Property<string>("Email");

                    b.Property<string>("LiveAddress");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("PhoneNumber");

                    b.Property<string>("Surname");

                    b.Property<int?>("TransactionHistorysIdTH");

                    b.HasKey("IdUser");

                    b.HasIndex("CreditHistoriesIDCredit");

                    b.HasIndex("TransactionHistorysIdTH");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankSimulator.API.Models.Entity.CreditHistory", b =>
                {
                    b.Property<int>("IDCredit")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CreditAmmount");

                    b.Property<string>("CreditPaymentTime");

                    b.Property<string>("Date");

                    b.Property<int>("IDPersonTakinCredit");

                    b.Property<int>("RateOfIntrest");

                    b.Property<decimal>("RemainingCredit");

                    b.HasKey("IDCredit");

                    b.ToTable("CreditHistory");
                });

            modelBuilder.Entity("BankSimulator.API.Models.TransactionHistory", b =>
                {
                    b.Property<int>("IdTH")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdTransactionReceiver");

                    b.Property<decimal>("MoneyAfter");

                    b.Property<decimal>("MoneyBefore");

                    b.Property<string>("TitleOfTransaction");

                    b.HasKey("IdTH");

                    b.ToTable("TransactionHistories");
                });

            modelBuilder.Entity("BankSimulator.API.Models.Account", b =>
                {
                    b.HasOne("BankSimulator.API.Models.Entity.CreditHistory", "CreditHistories")
                        .WithMany()
                        .HasForeignKey("CreditHistoriesIDCredit");

                    b.HasOne("BankSimulator.API.Models.TransactionHistory", "TransactionHistorys")
                        .WithMany()
                        .HasForeignKey("TransactionHistorysIdTH");
                });
#pragma warning restore 612, 618
        }
    }
}
