// <auto-generated />
using System;
using BankSimulator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankSimulator.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190214184203_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankSimulator.API.Models.Account", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdTH");

                    b.Property<int?>("IdUserInfo");

                    b.Property<int?>("IdWealth");

                    b.Property<string>("login");

                    b.Property<string>("password");

                    b.HasKey("IdUser");

                    b.HasIndex("IdTH");

                    b.HasIndex("IdUserInfo");

                    b.HasIndex("IdWealth");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankSimulator.API.Models.TransactionHistory", b =>
                {
                    b.Property<int>("IdTH")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdTransactionReceiver");

                    b.Property<decimal>("MoneyAfter");

                    b.Property<decimal>("MoneyBefore");

                    b.Property<string>("TitleOfTransaction");

                    b.HasKey("IdTH");

                    b.ToTable("transactionHistories");
                });

            modelBuilder.Entity("BankSimulator.API.Models.User_Info", b =>
                {
                    b.Property<int>("IdUserInfo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthdate");

                    b.Property<string>("Email");

                    b.Property<string>("LiveAddress");

                    b.Property<int>("PhoneNumber");

                    b.HasKey("IdUserInfo");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("BankSimulator.API.Models.Wealth", b =>
                {
                    b.Property<int>("IdWealth")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cash");

                    b.HasKey("IdWealth");

                    b.ToTable("Wealths");
                });

            modelBuilder.Entity("BankSimulator.API.Models.Account", b =>
                {
                    b.HasOne("BankSimulator.API.Models.TransactionHistory", "TransactionHistory")
                        .WithMany()
                        .HasForeignKey("IdTH");

                    b.HasOne("BankSimulator.API.Models.User_Info", "User_Info")
                        .WithMany()
                        .HasForeignKey("IdUserInfo");

                    b.HasOne("BankSimulator.API.Models.Wealth", "Wealth")
                        .WithMany()
                        .HasForeignKey("IdWealth");
                });
#pragma warning restore 612, 618
        }
    }
}
